spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:users
    password: password
    username: sa
    driver-class-name: org.h2.Driver
    generate-unique-name: false
    name: users
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

server:
  port: 9000